#!/bin/sh
# Copyright 2024 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

echo window.wermhosttitle = \""$WERMHOSTTITLE"\"\;

cat <<'EOF'
(function () {
	/* Get a unique session ID. We can't use endpoint ID because that value
	is passed to other clients to identify who is connected to a session. */
	var sco, bar, coo;
	if (location.protocol != 'https:')		return;
	if (document.cookie.match(/\bwermsession=/))	return;

	sco = [];
	bar = new Uint8Array(16);
	crypto.getRandomValues(bar);
	bar.forEach(function (n) { sco.push(String.fromCharCode(n)) });
	coo = btoa(sco.join(''));
	document.cookie = 'wermsession=' + coo.replace(/==*$/, '');
})();

if (!window.wermhosttitle)
	window.wermhosttitle = location.host.replace(/^localhost:/, ':');
EOF
