#!/bin/sh
# Copyright 2023 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

if test -z "$WERMAUTHNUSER"; then
	WERMAUTHNUSER="$HOSTNAME:$USER"
fi

echo window.wermauthnuser = \""$WERMAUTHNUSER"\"\;
echo window.relyingparty = \""$WERMRELYINGPARTY"\"\;

echo -n "$WERMAUTHNUSER" | sha256sum | sed '
	s/ .*//
	s/../0x&,/g
	s/^/window.wermuserid = \[/
	s/,$/\];/
'

echo '#include "main.js"' | cpp -P -I$WERMSRCDIR "$@"
